fixes = {
    'Mike Graczyk': 'Michael Graczyk',
    'Mike Graezyk': 'Michael Graczyk',
    'Mike Gracyzk': 'Michael Graczyk',
    'and Corey Ryan': 'Corey Ryan',
    'Jacque Hilburn, The McKinney Courier': 'Jacque Hilburn, The McKinney Courier-Gazette',
    'Gazette \n        Steve Stoler': 'Steve Stoler',
    'Terry S. Bertling': 'Terry Scott Bertling',
    'Terry Langford': 'Terri Langford',
    'Steward Smith': 'Stewart Smith',
    'Steve SToler': 'Steve Stoler',
    'Sheila Herchkin': 'Sheila Hotchkins',
    'Rosana Ruiz': 'Rosanna Ruiz',
    'Robert Wernsmann': 'Robert Wernsman',
    'Rebecca Mullins': 'Rebecca Mullens',
    'Reba Mullens': 'Rebecca Mullens',
    'Randall Beamer': 'Randy Beamer',
    'Rachel Gleason': 'Rachael Gleason',
    'Pauline Arrillage': 'Pauline Arrillaga',
    'Paula Dietrich': 'Paula Dittrick',
    'Paula Dettrick': 'Paula Dittrick',
    'Michell Lyons': 'Michelle Lyons',
    '  ': ' ',
    'Megan Stacks': 'Megan Stack',
    'Mary Schalangenstein': 'Mary Schlangenstein',
    'Mark Babnieck': 'Mark Babineck',
    'Lisa Tow': 'Lisa Trow',
    'Lisa Sandburg': 'Lisa Sandberg',
    'Leigh-Ann Gideon': 'Leigh-Anne Gideon',
    'L.D. Phillips': 'L.P. Phillips',
    'LP Phillips': 'L.P. Phillips',
    'Ken Molestine': 'Ken Molestina',
    'Karen Wilkison': 'Karen Wilkerson',
    'Juan Luzano': 'Juan Lozano',
    'Juan Lozana': 'Juan Lozano',
    'Jorge Desantiago': 'Jorge DeSantiago',
    'Jorge Enrique DeSantiago': 'Jorge DeSantiago',
    'John Gonzales': 'John Gonzalez',
    'Jay Gorrnley': 'Jay Gormley',
    'Jay Goanley': 'Jay Gormley',
    'Jason Whiteley': 'Jason Whitely',
    'Jason Whitley': 'Jason Whitely',
    'Geoff Drnshel': 'Geoff Drushel',
    'G. L.': 'G.L.',
    'Deon Daughtery': 'Deon Daugherty',
    'Denis Davis': 'Denise Davis',
    'Dale Lozon': 'Dale Lezon',
    'Armando Villsranca': 'Armando Villafranca',
    'Allen Turner': 'Allan Turner',
    'Alan Turner': 'Allan Turner'
}